name: xarray-eopf
channels:
- conda-forge
dependencies:
  # Library Dependencies
  - aiohttp
  - dask
  - dask-image
  - fsspec
  - numba
  - numpy
  - pyproj
  - python >=3.11
  - requests
  - s3fs
  - xarray >=2024.10
  - xcube-resampling >=0.3.2
  - zarr >=2.11, <3
  # Development Dependencies - Tools
  - black
  - isort
  - mkdocs
  - mkdocs-autorefs
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings
  - mkdocstrings-python  
  - pytest
  - pytest-cov
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib
  - pystac-client
