name: eopf-xr
channels:
- conda-forge
dependencies:
  - python >=3.10
  # Library Dependencies
  - fsspec
  - numpy
  - xarray >=2024.10
  - zarr
  # Development Dependencies - Tools
  - black
  - isort
  - pytest
  - pytest-cov
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib
