name: eopf-xr
channels:
- conda-forge
dependencies:
  - python >=3.10
  # Library Dependencies
  - aiohttp
  - dask
  - dask-image
  - fsspec
  - numpy
  - pyproj
  - requests
  - s3fs
  - xarray >=2024.10
  - zarr >=2,<3.0
  # Development Dependencies - Tools
  - black
  - isort
  - mkdocs
  - mkdocs-autorefs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python  
  - pytest
  - pytest-cov
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib
