name: Unittest Tests

on:
  push:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout xcube-zenodo
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Run unit tests
        run: pytest tests/unit --cov=xarray_eopf --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
